### ISSUE TITLE
Illumina variant calling

### ISSUE THREAD

**Issue by Mahmoudbassuoni** [anands-repo/hello#4]
Hi,
I m trying to run the illumina variant calling as the readme file but I first got this error 
`Traceback (most recent call last):
  File "python/call.py", line 401, in <module>
    ref_prefix = get_reference_prefixes(args.ref)
  File "/home/ionadmin/hello/python/find_chr_prefixes.py", line 16, in get_reference_prefixes
    raise ValueError("Unknown chromosomal names, explicitly specify chromosomes")
ValueError: Unknown chromosomal names, explicitly specify chromosomes`

so I tried to --chromosome 22 as I am working on that one 
**but I got this error:** 
`INFO:root:Creating hotspot detection jobs
Traceback (most recent call last):
  File "/home/ionadmin/hello/python/createJobsDVFiltered.py", line 143, in <module>
    main(args)
  File "/home/ionadmin/hello/python/createJobsDVFiltered.py", line 125, in main
    doOneRegion(args, chromosome, None, None, outputPrefix)
  File "/home/ionadmin/hello/python/createJobsDVFiltered.py", line 33, in doOneRegion
    stop = len(cache)
  File "/home/ionadmin/hello/python/PySamFastaWrapper.py", line 13, in __len__
    return self.handle.get_reference_length(self.chrom);
  File "pysam/libcfaidx.pyx", line 347, in pysam.libcfaidx.FastaFile.get_reference_length
KeyError: '22'
INFO:root:Created jobs to create hotspots, running to generate hotspots
cat: /home/ionadmin/bassyouni/analysis/HELLO_VC/hotspots_source_bam___NA12877_chr22__bam_22_/jobs_chromosome22.sh: No such file or directory`
and that resulted in empty output files, I am not sure what could be the issue here. I tried to trace back the python scripts but couldn't get out a reason for the issue. 

I am working on fasta file for chr 22 as ref and bam file for the same chr as input and for the workdir I have created a new folder for it
**the code that I used:**
`python python/call.py --ibam /home/ionadmin/bassyouni/source_bam/NA12877_chr22.bam --ref /home/ionadmin/bassyouni/chr22.fa --chromosomes 22 --network models/illumina_multi_coverage_mapq_threshold_hg002_continue_run16.wrapper.dnn --num_threads 12 --workdir /home/ionadmin/bassyouni/analysis/HELLO_VC/ --mapq_threshold 5`

**Comment by anands-repo** [comment]
The  `Unknown chromosomal names, explicitly specify chromosomes` error happened because HELLO cannot find either `chr1,chr2,...chr22` in the reference or `1,2,...22` in the reference. It can happen due to different reasons:
1. The reference sequence you are using doesn't have all of the chromosomes, but the chromosomal naming falls into one of these two types (i.e., either `chr1,chr2 ..` or `1,2,...`).
2. The chromosomal numbering doesn't fall into these two numbering formats, but is something else.

So you are right that you need to provide, explicitly, the chromosomal names using `--chromosomes` option, because your case seems to be the same as item (1) above. However, inside your `chr22.fa` file, the  chromosome may be named `chr22` instead of `22`. When you provide `--chromosomes` option, HELLO will try to use it as it is.

One more requirement is there - both BAM and reference need to have the  same chromosomal naming convention. That is, if reference has chromosome named as "chr22", then BAM should also have "chr22", and not "22".

**Comment by Mahmoudbassuoni** [comment]
perfect!!  it's working now with the _chr22_ option for the `--chromosomes` flag. 
Thanks,
